name: core
description: A new Flutter package.
version: 0.0.1

publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  coffsy_design_system:
    path: ../coffsy_design_system
  #Packages dependencies
  dependencies:
    path: ../dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any

flutter:
