name: dependencies
description: A new Flutter package.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  shimmer: ^2.0.0
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.6
  flutter_launcher_icons: ^0.9.0
  youtube_player_flutter: ^8.0.0
  flutter_svg: ^0.22.0
  liquid_pull_to_refresh: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  lottie: ^1.0.1
  fluttertoast: ^8.0.7
  animated_card: ^2.0.0

  # Structure
  flutter_triple: ^1.2.7+2
  flutter_modular: ^5.0.2
  # flutter_modular:
  #   git:
  #     url: https://github.com/Flutterando/modular
  #     path: flutter_modular
  #     ref: ade72425962fdcdc30044b6e95e13527e4b4e367

  dartz: ^0.10.0-nullsafety.2

  # Others
  package_info: ^2.0.2
  feedback: ^2.0.0

  # Firebase
  firebase_performance: ^0.7.0
  firebase_remote_config: 0.10.0+3
  firebase_crashlytics: ^2.0.7
  firebase_analytics: ^8.1.2
  firebase_storage: ^10.0.2

  # Core
  shared_preferences: ^2.0.6
  equatable: ^2.0.2
  dio: ^4.0.0
  effective_dart: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
