name: dependencies
description: A new Flutter package.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  shimmer: ^2.0.0
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.6
  flutter_launcher_icons: ^0.9.0
  package_info: ^2.0.2
  youtube_player_flutter: ^8.0.0
  flutter_svg: ^0.22.0
  liquid_pull_to_refresh: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  lottie: ^1.0.1 
  fluttertoast: ^8.0.7  
  dartz: ^0.10.0-nullsafety.2  
  flutter_modular: ^3.4.0-dev.4
  flutter_triple: ^1.2.4+3
  animated_card: ^2.0.0
  #firebase
  firebase_performance: ^0.7.0
  firebase_remote_config: 0.10.0+3
  firebase_crashlytics: ^2.0.7
  firebase_analytics: ^8.1.2
  # Core
  shared_preferences: ^2.0.6
  equatable: ^2.0.2  
  dio: ^4.0.0  
  effective_dart: ^1.3.2  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
